"""Regressions found while auditing every write_meshdict() caller for the
BL-contract / patch-typing bugs already fixed in watertight.py and the main
GUI's RetryRunner fallback.

Same bug, found duplicated in three more places:
- fault_tolerant.py and mesh_engine.py stored/emitted BL params using the
  pre-fix contract (thickness_ratio as a first-layer FRACTION plus a separate
  expansionRatio) and never passed patch_names — same silent-failure pattern
  as watertight.py: layers collapse (sub-1 "growth ratio" clamped to a
  default, no absolute first layer ever emitted) and inlet/outlet patches
  revert to cfMesh's default `wall` type.
- optimizer.py's fix loop had the identical BL-contract bug, AND a separate,
  more serious defect: it created a RetryRunner and never called .run() on
  it, so the loop rewrote meshDict with relaxed parameters but re-checked the
  SAME unchanged mesh every iteration — it could never actually improve
  anything.
"""
from __future__ import annotations

import os
import shutil
import sys
import time
import types
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

try:  # cadquery/OCP native libs need their dir on PATH on Windows
    import OCP as _ocp

    _d = os.path.dirname(_ocp.__file__)
    if _d not in os.environ.get("PATH", ""):
        os.environ["PATH"] = _d + os.pathsep + os.environ.get("PATH", "")
except Exception:
    pass

import pytest

from _test_helpers import load_commercial_module, space_free_tmp_root

# OpenFOAM/cfMesh reject paths with spaces (the user's home dir has one).
WORK_ROOT = space_free_tmp_root() / "cfmesh_bench" / "bl_contract_regression_test"


def _real_meshes(names):
    """Real trimesh.Trimesh triangles — real enough for export_surface_file
    to actually write an STL, so it never needs stubbing."""
    import numpy as np
    trimesh = __import__("trimesh")

    out = []
    for i, name in enumerate(names):
        verts = np.array([[0, 0, i], [1, 0, i], [0, 1, i]], dtype=float)
        faces = np.array([[0, 1, 2]])
        m = trimesh.Trimesh(vertices=verts, faces=faces, process=False)
        m.metadata["name"] = name
        out.append(m)
    return out


def _fresh_dir() -> Path:
    d = WORK_ROOT / f"run_{int(time.time() * 1000)}"
    d.mkdir(parents=True, exist_ok=True)
    (d / "system").mkdir(exist_ok=True)
    return d


@pytest.fixture(scope="module", autouse=True)
def _cleanup():
    yield
    shutil.rmtree(WORK_ROOT, ignore_errors=True)


def test_fault_tolerant_meshdict_uses_real_bl_contract_and_patch_names():
    mod = load_commercial_module("fault_tolerant")
    case_dir = _fresh_dir()

    wf = mod.FaultTolerantWorkflow.__new__(mod.FaultTolerantWorkflow)
    wf._case_dir = case_dir
    wf._max_cell = 0.1
    wf._min_cell = 0.02
    wf._meshes = _real_meshes(["inlet", "outlet", "wall"])
    wf._bl_params = {"nLayers": 4, "thicknessRatio": 0.02, "expansionRatio": 1.3}

    wf._step_prepare_meshdict()

    content = (case_dir / "system" / "meshDict").read_text()
    assert "renameBoundary" in content
    assert "thicknessRatio          1.3;" in content  # growth ratio, not 0.02
    assert "expansionRatio" not in content
    assert "maxFirstLayerThickness" in content  # 0.02 * 0.1 = 0.002, must be emitted


def test_mesh_engine_meshdict_uses_real_bl_contract_and_patch_names(monkeypatch):
    mod = load_commercial_module("mesh_engine")
    case_dir = _fresh_dir()

    engine = mod.MeshEngine.__new__(mod.MeshEngine)
    engine._of_config = types.SimpleNamespace()
    engine._params = types.SimpleNamespace(
        cell_size_multiplier=1.0, max_cell=0.1, min_cell=0.02,
        bl_enabled=True, bl_n_layers=5,
    )
    meshes = _real_meshes(["inlet", "outlet", "wall"])

    monkeypatch.setattr(engine, "_run_cartesian_mesh_sync", lambda cd: True)
    engine._run_cartesian_hex(case_dir, meshes)

    content = (case_dir / "system" / "meshDict").read_text()
    assert "renameBoundary" in content
    assert "thicknessRatio          1.2;" in content
    assert "maxFirstLayerThickness" in content


def test_mesh_engine_actually_waits_for_cartesianmesh_before_returning(monkeypatch):
    """_run_cartesian_hex used to fire RetryRunner.run() (async, QThread-based
    — completion delivered via a QueuedConnection signal that needs a running
    Qt event loop) and immediately return, racing the real meshing every time.
    Any headless/CLI caller (no Qt event loop at all) would then check
    quality / count cells against a polyMesh that wasn't written yet,
    silently reporting a "successful" 0-cell mesh. Verified live against a
    real WSL cartesianMesh run before this fix: it always reported 0 cells
    even though the mesh had actually been generated by the time the process
    exited. _run_cartesian_hex must now block on a real subprocess call."""
    mod = load_commercial_module("mesh_engine")
    case_dir = _fresh_dir()

    engine = mod.MeshEngine.__new__(mod.MeshEngine)
    engine._of_config = types.SimpleNamespace(build_command=lambda cd: ["true"])
    engine._params = types.SimpleNamespace(
        cell_size_multiplier=1.0, max_cell=0.1, min_cell=0.02,
        bl_enabled=False, bl_n_layers=0,
    )
    meshes = _real_meshes(["wall"])

    calls: list[bool] = []

    def fake_run(cmd, **kw):
        calls.append(True)
        return types.SimpleNamespace(returncode=0)

    monkeypatch.setattr("subprocess.run", fake_run)
    engine._run_cartesian_hex(case_dir, meshes)

    assert calls, "_run_cartesian_hex must actually invoke cartesianMesh synchronously"


def test_mesh_engine_retries_without_bl_when_cartesian_hex_fails(monkeypatch):
    """Mirrors RetryRunner's own BL-failure fallback: retry once with
    boundary layers stripped rather than failing the whole algorithm."""
    mod = load_commercial_module("mesh_engine")
    case_dir = _fresh_dir()

    engine = mod.MeshEngine.__new__(mod.MeshEngine)
    engine._of_config = types.SimpleNamespace()
    engine._params = types.SimpleNamespace(
        cell_size_multiplier=1.0, max_cell=0.1, min_cell=0.02,
        bl_enabled=True, bl_n_layers=5,
    )
    meshes = _real_meshes(["wall"])

    attempts = {"n": 0}

    def fake_sync(cd):
        attempts["n"] += 1
        return attempts["n"] > 1  # fail first (with BL), succeed on retry (no BL)

    monkeypatch.setattr(engine, "_run_cartesian_mesh_sync", fake_sync)
    engine._run_cartesian_hex(case_dir, meshes)

    assert attempts["n"] == 2
    content = (case_dir / "system" / "meshDict").read_text()
    assert "boundaryLayers" not in content


def test_optimizer_actually_reruns_cartesianmesh_and_uses_real_bl_contract(monkeypatch):
    """The more serious bug: the fix loop used to create a RetryRunner and
    never call .run() — it rewrote meshDict but re-checked the same
    unmodified mesh every iteration, so it could never converge. Also checks
    the same BL-contract bug found in the other modules above."""
    mod = load_commercial_module("optimizer")
    case_dir = _fresh_dir()

    calls = {"cartesian_mesh": 0}

    engine = mod.MeshOptimizer.__new__(mod.MeshOptimizer)
    engine._of_config = types.SimpleNamespace()

    def fake_remesh(cd):
        calls["cartesian_mesh"] += 1
        return True

    engine._run_cartesian_mesh = fake_remesh

    # load_commercial_module saves/restores sys.modules["polyfoammesh.core"]
    # around the exec-load above, so the real module is import-able again here.
    from polyfoammesh.core.openfoam_runner import MeshQualityReport

    # Two checkMesh calls: first fails (triggers a fix), second passes.
    reports = iter([
        MeshQualityReport(cells=100, max_skewness=9.0, max_non_ortho=10.0, max_aspect_ratio=5.0),
        MeshQualityReport(cells=100, max_skewness=0.5, max_non_ortho=10.0, max_aspect_ratio=5.0),
    ])
    engine._run_checkmesh = lambda cd: next(reports)

    report = engine.optimize(case_dir, max_iterations=3)

    assert calls["cartesian_mesh"] == 1, (
        "optimize() must actually re-run cartesianMesh once a fix is applied"
    )
    assert report.converged is True

    content = (case_dir / "system" / "meshDict").read_text()
    assert "thicknessRatio          1.2;" in content
    assert "expansionRatio" not in content
    assert "maxFirstLayerThickness" in content
